spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  temporal:
    connection:
      target: localhost:7233
    namespace: default
  batch:
    job:
      enabled: false
    jdbc:
      table-prefix: batch.BATCH_

mybatis:
  mapper-locations: classpath:mappers/*.xml
